//
//  MockedSubscriptType+ParsingError.swift
//
//  Copyright © 2026 Fetch.
//

import Foundation

extension MockedSubscriptType {

    /// A parsing error generated by ``MockedSubscriptType``.
    enum ParsingError: CaseIterable, CustomStringConvertible, Error {

        // MARK: Cases

        /// An error indicating that ``MockedSubscriptType`` was unable to parse
        /// a valid instance from the provided macro argument.
        case unableToParseSubscriptType

        /// An error indicating that ``MockedSubscriptType`` was unable to parse
        /// a valid async effect specifier.
        case unableToParseAsyncEffectSpecifier

        /// An error indicating that ``MockedSubscriptType`` was unable to parse
        /// a valid throws effect specifier.
        case unableToParseThrowsEffectSpecifier

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .unableToParseSubscriptType:
                "Unable to parse subscript type."
            case .unableToParseAsyncEffectSpecifier:
                "Unable to parse async effect specifier."
            case .unableToParseThrowsEffectSpecifier:
                "Unable to parse throws effect specifier."
            }
        }
    }
}
