//
//  MockedSubscriptMacro+MacroError.swift
//
//  Copyright © 2026 Fetch.
//

import Foundation

extension MockedSubscriptMacro {

    /// An error generated by ``MockedSubscriptMacro``.
    enum MacroError: CaseIterable, CustomStringConvertible, Error {

        // MARK: Cases

        /// An error indicating that the `@_MockedSubscript` macro can only be
        /// applied to subscript declarations.
        case canOnlyBeAppliedToSubscriptDeclarations

        /// An error indicating that the `@_MockedSubscript` macro was not
        /// passed any arguments.
        case noArguments

        /// An error indicating that the `@_MockedSubscript` macro was unable to
        /// parse the provided `subscriptType` argument.
        case unableToParseSubscriptTypeArgument

        /// An error indicating that the `@_MockedSubscript` macro was unable to
        /// parse the provided `mockName` argument.
        case unableToParseMockNameArgument

        /// An error indicating that the `@_MockedSubscript` macro was unable to
        /// parse the provided `isMockAnActor` argument.
        case unableToParseIsMockAnActorArgument

        /// An error indicating that the `@_MockedSubscript` macro was unable to
        /// parse the provided `mockSubscriptName` argument.
        case unableToParseMockSubscriptNameArgument

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .canOnlyBeAppliedToSubscriptDeclarations:
                "@_MockedSubscript can only be applied to subscript declarations."
            case .noArguments:
                "@_MockedSubscript was not passed any arguments."
            case .unableToParseSubscriptTypeArgument:
                "@_MockedSubscript was unable to parse the provided `subscriptType` argument."
            case .unableToParseMockNameArgument:
                "@_MockedSubscript was unable to parse the provided `mockName` argument."
            case .unableToParseIsMockAnActorArgument:
                "@_MockedSubscript was unable to parse the provided `isMockAnActor` argument."
            case .unableToParseMockSubscriptNameArgument:
                "@_MockedSubscript was unable to parse the provided `mockSubscriptName` argument."
            }
        }
    }
}
