name: Bug Report
description: Report a bug or unexpected behavior in the Swift package
title: "[Bug] <brief description>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 👋 Thanks for reporting a bug!
        Please fill out the form below so we can help you faster.

  - type: input
    id: swift_version
    attributes:
      label: Swift Version
      placeholder: "e.g., 5.9"
    validations:
      required: false

  - type: input
    id: package_version
    attributes:
      label: Package Version
      placeholder: "e.g., 1.2.0 or main"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps needed to reproduce the issue.
      placeholder: |
        1. Import the package
        2. Call `someFunction()`
        3. See crash or error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Stack Trace / Logs
      description: Paste any error messages or logs.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add screenshots, links to related issues, or any other useful info.
    validations:
      required: false
