name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] <brief description>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Got an idea?
        Share your feature request or enhancement so we can consider adding it.

  - type: input
    id: use_case
    attributes:
      label: Use Case
      description: What problem does this feature solve?
      placeholder: "I'm trying to..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Feature Proposal
      description: Describe the feature you’d like to see.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds?
      placeholder: "I've tried..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add screenshots, examples, or any other helpful information.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fetch-rewards/swift-mocking/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
