//
//  MockedError.swift
//  MockedMacros
//
//  Created by Gray Campbell on 11/4/23.
//

import Foundation

/// An error generated by ``MockedMacro``.
public enum MockedError: CaseIterable, CustomStringConvertible, Error {

    // MARK: Cases

    /// An error indicating that the `@Mocked` macro can only be applied to
    /// protocol declarations.
    case canOnlyBeAppliedToProtocols

    // MARK: Properties

    /// The description of the error.
    public var description: String {
        switch self {
        case .canOnlyBeAppliedToProtocols:
            "@Mocked can only be applied to protocols"
        }
    }
}
