//
//  MockedMethodMacro+MacroError.swift
//  MockedMacros
//
//  Created by Gray Campbell on 1/15/25.
//

import Foundation

extension MockedMethodMacro {

    /// An error generated by ``MockedMethodMacro``.
    enum MacroError: CaseIterable, CustomStringConvertible, Error {

        // MARK: Cases

        /// An error indicating that the `@MockedMethod` macro can only be
        /// applied to method declarations.
        case canOnlyBeAppliedToMethodDeclarations

        /// An error indicating that the `@MockedMethod` macro was not passed
        /// any arguments.
        case noArguments

        /// An error indicating that the `@MockedMethod` macro was unable to
        /// parse the provided `mockName` argument.
        case unableToParseMockNameArgument

        /// An error indicating that the `@MockedMethod` macro was unable to
        /// parse the provided `isMockAnActor` argument.
        case unableToParseIsMockAnActorArgument

        /// An error indicating that the `@MockedMethod` macro was unable to
        /// parse the provided `mockMethodName` argument.
        case unableToParseMockMethodName

        /// An error indicating that the `@MockedMethod` macro was passed more
        /// arguments than expected.
        case tooManyArguments

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .canOnlyBeAppliedToMethodDeclarations:
                "@MockedMethod can only be applied to method declarations."
            case .noArguments:
                "@MockedMethod was not passed any arguments."
            case .unableToParseMockNameArgument:
                "@MockedMethod was unable to parse `mockName` argument."
            case .unableToParseIsMockAnActorArgument:
                "@MockedMethod was unable to parse `isMockAnActor` argument."
            case .unableToParseMockMethodName:
                "@MockedMethod was unable to parse `mockMethodName` argument."
            case .tooManyArguments:
                "@MockedMethod was passed too many arguments."
            }
        }
    }
}
