//
//  MockedPropertyMacro+MacroError.swift
//  MockedMacros
//
//  Created by Gray Campbell on 1/17/25.
//

import Foundation

extension MockedPropertyMacro {

    /// An error generated by ``MockedPropertyMacro``.
    enum MacroError: CaseIterable, CustomStringConvertible, Error {

        // MARK: Cases

        /// An error indicating that the `@MockedProperty` macro can only be
        /// applied to property declarations.
        case canOnlyBeAppliedToPropertyDeclarations

        /// An error indicating that the `@MockedProperty` macro can only be
        /// applied to a single-binding property declaration.
        case canOnlyBeAppliedToSingleBindingPropertyDeclarations

        /// An error indicating that the `@MockedProperty` macro was not passed
        /// any arguments.
        case noArguments

        /// An error indicating that the `@MockedProperty` macro was unable to
        /// parse the provided `propertyType` argument.
        case unableToParsePropertyTypeArgument

        /// An error indicating that the `@MockedProperty` macro was unable to
        /// parse the provided `mockName` argument.
        case unableToParseMockNameArgument

        /// An error indicating that the `@MockedProperty` macro was unable to
        /// parse the provided `isMockAnActor` argument.
        case unableToParseIsMockAnActorArgument

        /// An error indicating that the `@MockedProperty` macro was passed more
        /// arguments than expected.
        case tooManyArguments

        /// An error indicating that the `@MockedProperty` macro was unable to
        /// parse the property binding's name.
        case unableToParsePropertyBindingName

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .canOnlyBeAppliedToPropertyDeclarations:
                "@MockedProperty can only be applied to property declarations."
            case .canOnlyBeAppliedToSingleBindingPropertyDeclarations:
                "@MockedProperty can only be applied to single-binding property declarations."
            case .noArguments:
                "@MockedProperty was not passed any arguments."
            case .unableToParsePropertyTypeArgument:
                "@MockedProperty was unable to parse `propertyType` argument."
            case .unableToParseMockNameArgument:
                "@MockedProperty was unable to parse `mockName` argument."
            case .unableToParseIsMockAnActorArgument:
                "@MockedProperty was unable to parse `isMockAnActor` argument."
            case .tooManyArguments:
                "@MockedProperty was passed too many arguments."
            case .unableToParsePropertyBindingName:
                "@MockedProperty was unable to parse the property binding's name."
            }
        }
    }
}
