//
//  MockableError.swift
//  MockableMacros
//
//  Created by Gray Campbell on 11/4/23.
//

import Foundation

/// An error generated by ``MockableMacro``.
public enum MockableError: CaseIterable, CustomStringConvertible, Error {

    // MARK: Cases

    /// An error indicating that the `@Mockable` macro can only be applied to
    /// protocol declarations.
    case canOnlyBeAppliedToProtocols

    // MARK: Properties

    /// The description of the error.
    public var description: String {
        switch self {
        case .canOnlyBeAppliedToProtocols:
            "@Mockable can only be applied to protocols"
        }
    }
}
