//
//  MockedMembersMacro+MacroError.swift
//  MockedMacros
//
//  Created by Gray Campbell on 1/15/25.
//

import SwiftSyntax

extension MockedMembersMacro {

    /// An error generated by ``MockedMembersMacro``.
    enum MacroError: CaseIterable, CustomStringConvertible, Error {

        // MARK: Cases

        /// An error indicating that the `@MockedMembers` macro can only be
        /// applied to class and actor declarations.
        case canOnlyBeAppliedToClassesAndActors

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .canOnlyBeAppliedToClassesAndActors:
                "@MockedMembers can only be applied to classes and actors."
            }
        }
    }
}
